language: java

jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

# this is the script run in the test stage
script: "mvn test -Dmaven.test.redirectTestOutputToFile -B"

deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Dmaven.test.redirectTestOutputToFile"
    on:
      branch: master
      tags: true
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Dmaven.test.redirectTestOutputToFile"
    on:
      branch: develop
